version: '3'
services:
  frontend:
    image: frontend-image
    container_name: frontend

  backend:
    image: backend-image
    container_name: backend

  nginx:
    image: nginx-image
    container_name: nginx
    ports:
      - "20112:20112"
    depends_on:
      - frontend
      - backend

